Update 0-run

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,13 +1,10 @@
 #!/bin/bash
 
-# Get the Python file name from the environment variable
-python_file="$PYFILE"
-
-# Check if the Python file exists
-if [ -f "$python_file" ]; then
-    # Run the Python script
-    python3 "$python_file"
-else
-    echo "Python file not found: $python_file"
-    exit 1
+# Check if the PYFILE environment variable is set
+if [ -z "$PYFILE" ]; then
+	echo "Error: PYFILE environment variable is not set."
+	exit 1
 fi
+
+# Run the Python script
+python3 "$PYFILE"
